api:
  http: ':3002'
log:
  level: error
data_providers:
  - tag: data_provider_cnipdb
    auto_reload: true
    file: '/etc/mosdns/data/GeoIP_CNIPDb.txt'
plugins:
  - tag: forward_query_to_local_alidns
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          enable_pipeline: false
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          enable_pipeline: false
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200::1]:853'
          enable_pipeline: false
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200:baba::1]:853'
          enable_pipeline: false
          idle_timeout: 5
          max_conns: 4
          trusted: true
  - tag: forward_query_to_local_dnspod
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
  - tag: forward_query_to_remote_google
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8844]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8888]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8844]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8888]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_query_to_remote_opendns
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccc::2]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccd::2]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccc::2]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccd::2]:853'
          enable_pipeline: true
          idle_timeout: 5
          max_conns: 4
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:data_provider_cnipdb'
  - tag: response_has_valid_rcode
    type: response_matcher
    args:
      rcode: [0]
  - tag: set_edns0_bufsize
    type: bufsize
    args:
      size: 1232
  - tag: set_edns0_client_subnet
    type: ecs
    args:
      auto: true
      mask4: 24
      mask6: 56
  - tag: main_server
    type: sequence
    args:
      exec:
        - _enable_response_padding
        - _misc_optm
        - set_edns0_bufsize
        - set_edns0_client_subnet
        - _pad_query
        - primary:
            - parallel:
                - - forward_query_to_local_alidns
                - - forward_query_to_local_dnspod
            - if: '(! response_has_local_ip) || (! response_has_valid_rcode)'
              exec:
                - _drop_response
          secondary:
            - parallel:
                - - forward_query_to_remote_google
                - - forward_query_to_remote_opendns
          fast_fallback: 250
servers:
  - exec: main_server
    listeners:
      - protocol: tls
        addr: ':8853'
        cert: '/etc/mosdns/cert/fullchain.cer'
        key: '/etc/mosdns/cert/zhijie.online.key'
