log:
  level: error
data_providers:
  - tag: data_provider_cnipdb
    auto_reload: true
    file: '/etc/mosdns/data/GeoIP_CNIPDb.txt'
plugins:
  - tag: forward_query_to_local_360
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.360.cn'
          dial_addr: '101.226.4.6:853'
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '123.125.81.6:853'
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '140.207.198.6:853'
          trusted: true
        - addr: 'tls://dot.360.cn'
          dial_addr: '218.30.118.6:853'
          trusted: true
  - tag: forward_query_to_local_alidns
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200::1]:853'
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200:baba::1]:853'
          trusted: true
  - tag: forward_query_to_local_cfiec
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.ipv6dns.com'
          dial_addr: '221.228.217.28:853'
          trusted: true
        - addr: 'tls://dns.ipv6dns.com'
          dial_addr: '[240e:e9:900b::5]:853'
          trusted: true
  - tag: forward_query_to_local_dnspod
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
          trusted: true
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          trusted: true
  - tag: forward_query_to_remote_adguard
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '94.140.14.140:853'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '94.140.14.141:853'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '[2a10:50c0::1:ff]:853'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '[2a10:50c0::2:ff]:853'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '94.140.14.140:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '94.140.14.141:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '[2a10:50c0::1:ff]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns-unfiltered.adguard.com'
          dial_addr: '[2a10:50c0::2:ff]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_query_to_remote_google
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8844]:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8888]:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8844]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8888]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_query_to_remote_opendns
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccc::2]:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccd::2]:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccc::2]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccd::2]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_query_to_remote_quad9
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '149.112.112.11:853'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '9.9.9.11:853'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '[2620:fe::11]:853'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '[2620:fe::fe:11]:853'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '149.112.112.11:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '9.9.9.11:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '[2620:fe::11]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns11.quad9.net'
          dial_addr: '[2620:fe::fe:11]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: query_is_in_cache
    type: cache
    args:
      cache_everything: true
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 30
      redis: 'redis://127.0.0.1:6379/0'
      redis_timeout: 125
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:data_provider_cnipdb'
  - tag: rewrite_max_min_ttl
    type: ttl
    args:
      maximum_ttl: 3600
      minimal_ttl: 300
  - tag: set_edns0_bufsize
    type: bufsize
    args:
      size: 1232
  - tag: set_edns0_client_subnet
    type: ecs
    args:
      auto: true
      mask4: 24
      mask6: 56
  - tag: main_server
    type: sequence
    args:
      exec:
        - _enable_response_padding
        - _misc_optm
        - _single_flight
        - set_edns0_bufsize
        - set_edns0_client_subnet
        - _pad_query
        - query_is_in_cache
        - primary:
            - primary:
                - parallel:
                    - - forward_query_to_local_360
                    - - forward_query_to_local_cfiec
                - if: '! [_response_valid_answer]'
                  exec:
                    - _drop_response
              secondary:
                - parallel:
                    - - forward_query_to_local_alidns
                    - - forward_query_to_local_dnspod
              always_standby: true
              fast_fallback: 375
            - if: '! response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - primary:
                - parallel:
                    - - forward_query_to_remote_adguard
                    - - forward_query_to_remote_quad9
                - if: '! [_response_valid_answer]'
                  exec:
                    - _drop_response
              secondary:
                - parallel:
                    - - forward_query_to_remote_google
                    - - forward_query_to_remote_opendns
              always_standby: true
              fast_fallback: 375
          always_standby: true
          fast_fallback: 500
        - rewrite_max_min_ttl
servers:
  - exec: main_server
    listeners:
      - protocol: tls
        addr: '127.0.0.1:8853'
        cert: '/etc/mosdns/cert/fullchain.cer'
        key: '/etc/mosdns/cert/zhijie.online.key'
    timeout: 1
