log:
  level: info
plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - _single_flight
        - query_sequence
      server:
        - protocol: dot
          addr: 127.0.0.1:8853
          cert: '/etc/mosdns/cert/fullchain.cer'
          key: '/etc/mosdns/cert/zhijie.online.key'
      timeout: 1
  - tag: query_sequence
    type: sequence
    args:
      exec:
        - _enable_response_padding
        - _pad_query
        - set_ecs
        - set_edns0_bufsize
        - query_is_in_redis_cache
        - primary:
            - forward_query_to_local_dns
            - if:
                - '!response_is_local_ip'
                - _response_empty_answer
              exec:
                - _drop_response
          secondary:
            - forward_query_to_remote_dns
          always_standby: true
          fast_fallback: 500
  - tag: rewrite_max_min_ttl
    type: ttl
    args:
      maximum_ttl: 3600
      minimal_ttl: 300
  - tag: set_ecs
    type: ecs
    args:
      auto: true
      mask4: 24
      mask6: 56
  - tag: set_edns0_bufsize
    type: bufsize
    args:
      size: 1232
  - tag: query_is_in_memory_cache
    type: cache
    args:
      cache_everything: true
      lazy_cache_ttl: 3600
      lazy_cache_reply_ttl: 10
      size: 4096
  - tag: query_is_in_redis_cache
    type: cache
    args:
      cache_everything: true
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 30
      redis: 'redis://127.0.0.1:6379/0'
      redis_timeout: 250
  - tag: response_is_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:/etc/mosdns/data/GeoIP_CNIPDb.txt'
  - tag: verify_response_is_valid
    type: sequence
    args:
      exec:
        - if:
            - '!_response_rcode_success'
          exec:
            - _drop_response
  - tag: forward_query_to_local_dns
    type: sequence
    args:
      exec:
        - query_is_in_memory_cache
        - primary:
            - forward_to_dnspod
            - verify_response_is_valid
          secondary:
            - forward_to_alidns
          always_standby: true
          fast_fallback: 375
        - rewrite_max_min_ttl
  - tag: forward_query_to_remote_dns
    type: sequence
    args:
      exec:
        - query_is_in_memory_cache
        - primary:
            - forward_to_opendns
            - verify_response_is_valid
          secondary:
            - forward_to_google
          always_standby: true
          fast_fallback: 375
        - rewrite_max_min_ttl
  - tag: forward_to_alidns
    type: sequence
    args:
      exec:
        - primary:
            - forward_to_alidns_doh
            - verify_response_is_valid
          secondary:
            - forward_to_alidns_dot
          always_standby: true
          fast_fallback: 250
  - tag: forward_to_dnspod
    type: sequence
    args:
      exec:
        - primary:
            - forward_to_dnspod_doh
            - verify_response_is_valid
          secondary:
            - forward_to_dnspod_dot
          always_standby: true
          fast_fallback: 250
  - tag: forward_to_google
    type: sequence
    args:
      exec:
        - primary:
            - forward_to_google_doh
            - verify_response_is_valid
          secondary:
            - forward_to_google_dot
          always_standby: true
          fast_fallback: 250
  - tag: forward_to_opendns
    type: sequence
    args:
      exec:
        - primary:
            - forward_to_opendns_doh
            - verify_response_is_valid
          secondary:
            - forward_to_opendns_dot
          always_standby: true
          fast_fallback: 250
  - tag: forward_to_alidns_doh
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.5.5.5:443'
          enable_pipeline: false
          idle_timeout: 30
          max_conns: 16
          trusted: true
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
          enable_pipeline: false
          idle_timeout: 30
          max_conns: 16
          trusted: true
  - tag: forward_to_alidns_dot
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          enable_pipeline: true
          trusted: true
  - tag: forward_to_dnspod_doh
    type: fast_forward
    args:
      upstream:
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '1.12.12.12:443'
          enable_http3: false
          trusted: true
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '120.53.53.53:443'
          enable_http3: false
          trusted: true
  - tag: forward_to_dnspod_dot
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
          enable_pipeline: true
          trusted: true
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          enable_pipeline: true
          trusted: true
  - tag: forward_to_google_doh
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.4.4:443'
          enable_http3: false
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
          enable_http3: false
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_to_google_dot
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          enable_pipeline: true
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          enable_pipeline: true
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_to_opendns_doh
    type: fast_forward
    args:
      upstream:
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.220.2:443'
          enable_http3: false
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.222.2:443'
          enable_http3: false
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_to_opendns_dot
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          enable_pipeline: true
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          enable_pipeline: true
          socks5: '127.0.0.1:7890'
          trusted: true
