log:
  level: info
plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - _enable_response_padding
        - _pad_query
        - set_ecs
        - set_edns0_bufsize
        - main_sequence
        - final_sequence
        - store_response_to_memory
      server:
        - protocol: tcp
          addr: 127.0.0.1:5353
        - protocol: udp
          addr: 127.0.0.1:5353
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - modify_response
#        - if:
#            - query_is_ad_domain
#          exec:
#            - _block_with_servfail
#            - _return
        - primary:
            - forward_query_to_lan_dns
            - if:
                - '!_response_rcode_success'
              exec:
                - _drop_response
          secondary:
            - forward_query_to_wan_dns
          always_standby: true
          fast_fallback: 500
  - tag: final_sequence
    type: sequence
    args:
      exec:
#        - if:
#            - response_is_bogus_ip
#          exec:
#            - _block_with_servfail
#            - _return
        - if:
            - _response_rcode_success
          exec:
            - _return
          else_exec:
            - _block_with_servfail
  - tag: modify_response
    type: arbitrary
    args:
      rr:
        - 'vpn.zhijie.online IN A ANSWER vpn.zhijie.online. IN A 127.0.0.1'
        - 'vpn.zhijie.online IN AAAA ANSWER vpn.zhijie.online. IN AAAA ::1'
  - tag: set_ecs
    type: ecs
    args:
      auto: true
  - tag: set_edns0_bufsize
    type: bufsize
    args:
      size: 1232
  - tag: store_response_to_memory
    type: cache
    args:
      cache_everything: true
      lazy_cache_reply_ttl: 30
      lazy_cache_ttl: 86400
      size: 65536
  - tag: forward_query_to_lan_dns
    type: sequence
    args:
      exec:
        - load_balance:
            - forward_to_lan_dns53
  - tag: forward_query_to_wan_dns
    type: sequence
    args:
      exec:
        - load_balance:
            - forward_to_alidns
            - forward_to_dnspod
  - tag: forward_to_alidns
    type: sequence
    args:
      exec:
        - parallel:
            - forward_to_alidns_doh
            - forward_to_alidns_dot
  - tag: forward_to_dnspod
    type: sequence
    args:
      exec:
        - parallel:
            - forward_to_dnspod_doh
            - forward_to_dnspod_dot
  - tag: forward_to_alidns_doh
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.5.5.5:443'
          enable_pipeline: false
          idle_timeout: 30
          max_conns: 16
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
          enable_pipeline: false
          idle_timeout: 30
          max_conns: 16
  - tag: forward_to_alidns_dot
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          enable_pipeline: true
          idle_timeout: 10
          max_conns: 16
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          enable_pipeline: true
          idle_timeout: 10
          max_conns: 16
  - tag: forward_to_dnspod_doh
    type: fast_forward
    args:
      upstream:
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '1.12.12.12:443'
          enable_pipeline: false
          idle_timeout: 30
          max_conns: 16
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '120.53.53.53:443'
          enable_pipeline: false
          idle_timeout: 30
          max_conns: 16
  - tag: forward_to_dnspod_dot
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
          enable_pipeline: true
          idle_timeout: 10
          max_conns: 16
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
          enable_pipeline: true
          idle_timeout: 10
          max_conns: 16
  - tag: forward_to_lan_dns53
    type: fast_forward
    args:
      upstream:
        - addr: 'tcp://LAN_DNS_IP_ADDRESS'
          dial_addr: 'LAN_DNS_IP_ADDRESS:53'
          enable_pipeline: true
          max_conns: 16
        - addr: 'udpme://LAN_DNS_IP_ADDRESS'
          dial_addr: 'LAN_DNS_IP_ADDRESS:53'
          enable_pipeline: false
          max_conns: 16
#  - tag: query_is_ad_domain
#    type: query_matcher
#    args:
#      domain:
#        - 'ext:./geosite.dat:category-ads-all'
#        - 'ext:./AdFilter.txt'
  - tag: response_is_bogus_ip
    type: response_matcher
    args:
      ip:
        - '101.226.10.8/32'
        - '104.239.213.7/32'
        - '111.11.208.2/32'
        - '111.175.221.58/32'
        - '112.132.230.179/32'
        - '113.12.83.4/32'
        - '113.12.83.5/32'
        - '114.112.163.232/32'
        - '114.112.163.254/32'
        - '120.192.83.163/32'
        - '120.209.138.64/32'
        - '123.125.81.12/32'
        - '123.129.254.11/32'
        - '123.129.254.12/32'
        - '123.129.254.13/32'
        - '123.129.254.14/32'
        - '123.129.254.15/32'
        - '123.129.254.16/32'
        - '123.129.254.17/32'
        - '123.129.254.18/32'
        - '123.129.254.19/32'
        - '124.232.132.94/32'
        - '125.211.213.130/32'
        - '125.211.213.131/32'
        - '125.211.213.132/32'
        - '125.211.213.133/32'
        - '125.211.213.134/32'
        - '125.76.239.244/32'
        - '125.76.239.245/32'
        - '180.153.103.224/32'
        - '180.168.41.175/32'
        - '183.207.232.253/32'
        - '183.221.242.172/32'
        - '183.221.250.11/32'
        - '183.224.40.24/32'
        - '198.105.254.11/32'
        - '202.100.220.54/32'
        - '202.100.68.117/32'
        - '202.102.110.203/32'
        - '202.102.110.204/32'
        - '202.102.110.205/32'
        - '202.106.199.34/32'
        - '202.106.199.35/32'
        - '202.106.199.36/32'
        - '202.106.199.37/32'
        - '202.106.199.38/32'
        - '202.98.24.121/32'
        - '202.98.24.122/32'
        - '202.98.24.123/32'
        - '202.98.24.124/32'
        - '202.98.24.125/32'
        - '202.99.254.230/32'
        - '202.99.254.231/32'
        - '202.99.254.232/32'
        - '211.136.113.1/32'
        - '211.137.130.101/32'
        - '211.138.102.198/32'
        - '211.138.74.132/32'
        - '211.139.136.73/32'
        - '211.98.70.226/32'
        - '211.98.70.227/32'
        - '211.98.71.195/32'
        - '218.28.144.36/32'
        - '218.28.144.37/32'
        - '218.28.144.38/32'
        - '218.28.144.39/32'
        - '218.28.144.40/32'
        - '218.28.144.41/32'
        - '218.28.144.42/32'
        - '218.30.64.194/32'
        - '218.68.250.117/32'
        - '218.68.250.118/32'
        - '218.68.250.119/32'
        - '218.68.250.120/32'
        - '218.68.250.121/32'
        - '219.146.13.36/32'
        - '220.165.8.172/32'
        - '220.165.8.174/32'
        - '220.250.64.18/32'
        - '220.250.64.19/32'
        - '220.250.64.20/32'
        - '220.250.64.21/32'
        - '220.250.64.22/32'
        - '220.250.64.225/32'
        - '220.250.64.226/32'
        - '220.250.64.227/32'
        - '220.250.64.228/32'
        - '220.250.64.23/32'
        - '220.250.64.24/32'
        - '220.250.64.25/32'
        - '220.250.64.26/32'
        - '220.250.64.27/32'
        - '220.250.64.28/32'
        - '220.250.64.29/32'
        - '220.250.64.30/32'
        - '221.179.46.190/32'
        - '221.179.46.194/32'
        - '221.192.153.41/32'
        - '221.192.153.42/32'
        - '221.192.153.43/32'
        - '221.192.153.44/32'
        - '221.192.153.45/32'
        - '221.192.153.46/32'
        - '221.192.153.49/32'
        - '221.204.244.36/32'
        - '221.204.244.37/32'
        - '221.204.244.38/32'
        - '221.204.244.39/32'
        - '221.204.244.40/32'
        - '221.204.244.41/32'
        - '222.221.5.204/32'
        - '222.221.5.252/32'
        - '222.221.5.253/32'
        - '223.82.248.117/32'
        - '23.217.138.108/32'
        - '42.123.125.237/32'
        - '60.19.29.21/32'
        - '60.19.29.22/32'
        - '60.19.29.23/32'
        - '60.19.29.24/32'
        - '60.19.29.25/32'
        - '60.19.29.26/32'
        - '60.19.29.27/32'
        - '60.191.124.236/32'
        - '60.191.124.252/32'
        - '61.131.208.210/32'
        - '61.131.208.211/32'
        - '61.139.8.101/32'
        - '61.139.8.102/32'
        - '61.139.8.103/32'
        - '61.139.8.104/32'
        - '61.183.1.186/32'
        - '61.191.206.4/32'
