log:
  level: error
data_providers:
  - tag: data_provider_cnipdb
    auto_reload: true
    file: '/etc/mosdns/data/GeoIP_CNIPDb.txt'
plugins:
  - tag: forward_to_alidns
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.5.5.5:443'
          trusted: true
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
          trusted: true
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '[2400:3200::1]:443'
          trusted: true
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '[2400:3200:baba::1]:443'
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200::1]:853'
          enable_pipeline: false
          trusted: true
        - addr: 'tls://dns.alidns.com'
          dial_addr: '[2400:3200:baba::1]:853'
          enable_pipeline: false
          trusted: true
  - tag: forward_to_dnspod
    type: fast_forward
    args:
      upstream:
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '1.12.12.12:443'
          trusted: true
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '120.53.53.53:443'
          trusted: true
        - addr: 'tls://doh.pub'
          dial_addr: '1.12.12.12:853'
          trusted: true
        - addr: 'tls://doh.pub'
          dial_addr: '120.53.53.53:853'
          trusted: true
  - tag: forward_to_google
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.4.4:443'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '[2001:4860:4860::8844]:443'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '[2001:4860:4860::8888]:443'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8844]:853'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8888]:853'
          trusted: true
  - tag: forward_to_google_proxy
    type: fast_forward
    args:
      upstream:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.4.4:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '[2001:4860:4860::8844]:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://dns.google/dns-query'
          dial_addr: '[2001:4860:4860::8888]:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8844]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://dns.google'
          dial_addr: '[2001:4860:4860::8888]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_to_opendns
    type: fast_forward
    args:
      upstream:
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.220.2:443'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.222.2:443'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '[2620:0:ccc::2]:443'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '[2620:0:ccd::2]:443'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccc::2]:853'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccd::2]:853'
          trusted: true
  - tag: forward_to_opendns_proxy
    type: fast_forward
    args:
      upstream:
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.220.2:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '208.67.222.2:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '[2620:0:ccc::2]:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'https://sandbox.opendns.com/dns-query'
          dial_addr: '[2620:0:ccd::2]:443'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.220.2:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '208.67.222.2:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccc::2]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
        - addr: 'tls://sandbox.opendns.com'
          dial_addr: '[2620:0:ccd::2]:853'
          socks5: '127.0.0.1:7890'
          trusted: true
  - tag: forward_query_to_local_dns
    type: sequence
    args:
      exec:
        - primary:
            - forward_to_dnspod
            - if: '! [_response_valid_answer]'
              exec:
                - _drop_response
          secondary:
            - forward_to_alidns
          always_standby: true
          fast_fallback: 375
  - tag: forward_query_to_remote_dns
    type: sequence
    args:
      exec:
        - primary:
            - primary:
                - forward_to_opendns_proxy
                - if: '! [_response_valid_answer]'
                  exec:
                    - _drop_response
              secondary:
                - forward_to_opendns
                - if: '! [_response_valid_answer]'
                  exec:
                    - _drop_response
              always_standby: true
              fast_fallback: 250
          secondary:
            - primary:
                - forward_to_google_proxy
                - if: '! [_response_valid_answer]'
                  exec:
                    - _drop_response
              secondary:
                - forward_to_google
              always_standby: true
              fast_fallback: 250
          always_standby: true
          fast_fallback: 375
  - tag: query_is_in_cache
    type: cache
    args:
      cache_everything: true
      lazy_cache_ttl: 86400
      lazy_cache_reply_ttl: 30
      redis: 'redis://127.0.0.1:6379/0'
      redis_timeout: 125
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'provider:data_provider_cnipdb'
  - tag: rewrite_max_min_ttl
    type: ttl
    args:
      maximum_ttl: 3600
      minimal_ttl: 300
  - tag: set_edns0_bufsize
    type: bufsize
    args:
      size: 1232
  - tag: set_edns0_client_subnet
    type: ecs
    args:
      auto: true
      mask4: 24
      mask6: 56
  - tag: main_server
    type: sequence
    args:
      exec:
        - _enable_response_padding
        - _misc_optm
        - _single_flight
        - set_edns0_bufsize
        - set_edns0_client_subnet
        - _pad_query
        - query_is_in_cache
        - primary:
            - forward_query_to_local_dns
            - if: '! response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_query_to_remote_dns
          always_standby: true
          fast_fallback: 500
        - rewrite_max_min_ttl
servers:
  - exec: main_server
    listeners:
      - protocol: tls
        addr: '127.0.0.1:8853'
        cert: '/etc/mosdns/cert/fullchain.cer'
        key: '/etc/mosdns/cert/zhijie.online.key'
    timeout: 1
